### ISSUE TITLE
New Pusher Images

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/coulombs-law#10]
After trying to reuse the pusher images from https://github.com/phetsims/forces-and-motion-basics, we ran into some trouble. It appears that the ratios of image height to hand height differ between the puller and pusher artwork (in addition to the gray circular surface on which the figures stand).

Both images below have the same vertical offset.

<img width="691" alt="screen shot 2017-07-12 at 11 38 24 am" src="https://user-images.githubusercontent.com/5711147/28131588-98e2e692-66f7-11e7-9c33-cf1d6345a7fb.png">

<img width="624" alt="screen shot 2017-07-12 at 11 38 38 am" src="https://user-images.githubusercontent.com/5711147/28131587-98e22b30-66f7-11e7-933d-5606b84a55ee.png">

@arouinfar do we have other images that I'm not aware of yet, or will we need to create entirely new pusher artwork?

**Comment by jessegreenberg** [comment]
There is a big difference in the shadow too.

**Comment by jessegreenberg** [comment]
@mbarlow12 found that the shadows are drawn by the sim, so we can correct that much.  We were also wondering if the difference in shadow is what is messing with the alignment.

**Comment by arouinfar** [comment]
@jessegreenberg @mbarlow12 I prefer the shadows in the top image. 

I can also try aligning the puller images with the pusher images and re-exporting them all at the same resolution.  The assets are similarly sized, so I won't need to resize the pusher assets.
![image](https://user-images.githubusercontent.com/8419308/28132534-57dbadac-66fa-11e7-9fb9-41e09f715946.png)

But I'd need to shift the pushers down so that the hands would be aligned with the rope, so the pushers will have lots of transparent space on the top, and the pullers would have extra space on the bottom.
![image](https://user-images.githubusercontent.com/8419308/28132561-7128a3a0-66fa-11e7-8523-bef31f561834.png)

I'm not sure if the transition from pushing to pulling will look odd with a vertical shift, but at the moment, I don't know what else to do. There would also need to be a bit of a horizontal shift so that the rope doesn't appear to impale the pusher's hands. In aggregate, the images would look something like this:
![image](https://user-images.githubusercontent.com/8419308/28132820-33d9febc-66fb-11e7-8e6c-d85146bba452.png)

@jessegreenberg @mbarlow12 I estimate that it will take me a few hours to properly align and export a new set of pushers and pullers that are identically sized and aligned with one another. This is mostly due to the artwork living in different layers, which cannot be individually exported from Illustrator, which makes things significantly more complicated. Please let me know if you would like me to proceed.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar.  We should be able to shift images down in the code, you shouldn't need to export new images if that is the best solution.

But we thought it might look strange to shift the pushers down like that.  Maybe we should give that a try and see how it looks.

Would it take a lot of effort to modify the  images so that the hands align with the puller images without having to shift images down? I think that would be the ideal solution.

**Comment by arouinfar** [comment]
@jessegreenberg please try shifting the images down. Maybe it won't look as odd as we suspect?

To avoid the vertical shift, I'd need to shrink the pushers so that their hands and feet are aligned with the pullers. I think a shrinking pusher would look stranger than the shifting puller. It would take significant changes to update the pusher (or puller) so that the hands and feet are on the same level, so I'd like to avoid that route if at all possible.

**Comment by ariel-phet** [comment]
@arouinfar Cheryl could also do image change up work for you

**Comment by jessegreenberg** [comment]
Another option: We could make a rigged RobotNode with Scenery so we have total control of what it looks like, and how it is positioned in any sim so we don't have to make new artwork when we need modified puller/pusher nodes in the future. Would be totally awesome, but would take a lot of time.

**Comment by arouinfar** [comment]
Initially, I was worried that we would have to alter the stances to level the hands, which would be complicated. After playing with the artwork a bit more, I realized that we could instead rotate the puller's arms about the shoulder so that their hands would be level with the puller. Here's a comparison showing a pusher with the min/max pullers:
![image](https://user-images.githubusercontent.com/8419308/28136517-38bf0f38-6707-11e7-9eb7-6454897b826e.png)
 
This is actually a pretty straight-forward solution. It'll take me about an hour to systematically shift all of the arms and ensure that everything's aligned, but I won't have time to get to it until tomorrow or Friday.

**Comment by jessegreenberg** [comment]
@arouinfar I think those are looking great! Thanks for working on it!

**Comment by arouinfar** [comment]
@jessegreenberg creating RobotNode in Scenery would be really cool, and I could see it being very handy for a sim like Moving Man. However, I think rotating the arms will be a way more efficient.

**Comment by mbarlow12** [comment]
Thanks @arouinfar! That'll be a big help.

**Comment by arouinfar** [comment]
I've emailed the updated puller assets to @mbarlow12 and @jessegreenberg.

**Comment by jessegreenberg** [comment]
Regarding
> https://github.com/phetsims/coulombs-law/issues/10#issuecomment-314876850

I totally agree, images are more efficient now.  If memory becomes an issue in forces-and-motion-basics or a sim that uses inverse-square-law-common, it could be another time to investigate a scenery drawn approach.  Those 32 images add up.

**Comment by mbarlow12** [comment]
Fixed in 7da0e30e8d963b721d35bad98cf326716f0bb001.
