### ISSUE TITLE
Force Values should display a magnitude

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#101]
For https://github.com/phetsims/QA/issues/243

The Force Values should display the magnitude of the force, and should never be negative. The vector shows the direction of the force, while the Force Value represents the magnitude only.

Currently, the Force Value displays a negative sign when the force is attractive.
![image](https://user-images.githubusercontent.com/8419308/50317932-7b70f680-047b-11e9-90fc-0fed8c4d6dae.png)

Better late than never, I suppose...

**Comment by ariel-phet** [comment]
@arouinfar a bit of a hairy question, because sometimes people teach that for the equation 

F=k*q1*q2/(r^2) that a negative result means attractive and a positive result means repulsive.

I don't personally like that approach to teaching Coulomb's law, and I also think that given the depiction in the sim, it is totally reasonable to think of the force value purely as a magnitude. It doesn't really have an intrinsic + or - sign to it.

So yes, I agree, just display the magnitude, always positive.

**Comment by arouinfar** [comment]
Looks good in rc.9. Thanks @mbarlow12!
