### ISSUE TITLE
Instrument  ruler with keyboard navigation

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#35]
All components in this sim are keyboard navigable except the ruler, @mbarlow12 could you please instrument the ruler with keyboard navigation? You will need to use KeyboardDragHandler in scenery-phet. Take a look at its usage in Friction for an example. Let me know if you have any questions or run into trouble.

If we do this before publishing a dev version this could be tested in the next dev test.

**Comment by mbarlow12** [comment]
Since all ISLC sims use a ModelViewTransform2, it will be useful to handle such situations in the KeyboardDragHandler itself.

See https://github.com/phetsims/scenery-phet/issues/344 and https://github.com/phetsims/scenery/issues/716 for more details.

**Comment by jessegreenberg** [comment]
@mbarlow12 and I worked on this 12/5/17 and keyboard dragging for the ruler is working great. @mbarlow12 anything else to do here or can this be closed?

**Comment by mbarlow12** [comment]
Was about to close then found this! Looks like we need to make sure that the ruler and its focus highlight are all on the top of the sim.
<img width="986" alt="screen shot 2018-01-02 at 2 17 37 pm" src="https://user-images.githubusercontent.com/5711147/34500413-d7465c8a-efc7-11e7-9768-5381bd3025fa.png">

**Comment by jessegreenberg** [comment]
Good catch @mbarlow12! This is really similar to https://github.com/phetsims/faradays-law/issues/87. Actually, is it problematic that the ruler is in front of all controls anyway?

**Comment by jessegreenberg** [comment]
In https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab_en.html the ruler is  layered behind the control panels to avoid occlusion issues, perhaps that is how this sim should behave too.

**Comment by mbarlow12** [comment]
@jessegreenberg that works for me. I'll make the update today.

**Comment by mbarlow12** [comment]
I'm running into a few issues. Since the panels are common to all sims, they're added to the scene graph first in the CommonView and are thus on the bottom 'layer'. Adding the ruler behind them results in the ruler also being behind the pushers:
<img width="734" alt="screen shot 2018-01-05 at 1 48 38 pm" src="https://user-images.githubusercontent.com/5711147/34627782-2d594f98-f21f-11e7-9cf7-4c10d222be2b.png">

Secondly, the highlights are still overlapping the controls:
<img width="704" alt="screen shot 2018-01-05 at 1 49 36 pm" src="https://user-images.githubusercontent.com/5711147/34627814-4c10b0fc-f21f-11e7-9a44-e067f1cd8e51.png">

Perhaps we don't care about the highlight overlap. It definitely seems less obtrusive than the control panel highlights overlapping the ruler (i.e. with the ruler on the top layer), but I'd still defer to someone with more a11y expertise on that topic. As to the layering of the ruler behind the pullers, we either need to
1) Rework the scene graph construction to allow for the ruler to be beneath the panels and above the pullers or
2) Get approval from the design team to have the ruler underneath the pullers.

@jessegreenberg do you have any ideas on how we might tackle 1? We're currently thinking of the CommonView as beginning the scene setup, but we could reverse the order so that the Atomic and Macro screens (and GFL, GFLB) initialize the layout bounds and model view transforms and the commonView simply appends the common elements.

**Comment by jessegreenberg** [comment]
The highlight overlap seems acceptable to me but it would be good to hear from @emily-phet and @terracoda.

Placing the ruler behind the charges/pullers makes it very difficult to measure the distance so I think the ruler will need to be above the charges and below the panels.

**Comment by jessegreenberg** [comment]
It seems like we will have to change the scene graph structure. Here are some possibilities
- Create the ruler in CoulombsLawCommonView, passing the options for each ruler in CoulombsLawCommonView.call()
- Pass the ChargeNodes and ISLCRuler into CoulombsLawCommonView as args and let the common view set the layering order.
- Something else?

@mbarlow12 what do you think?

**Comment by emily-phet** [comment]
A few thoughts:
- The ruler is going to be a challenge for auditory description, in fact I'm considering "a non-visually accessible ruler" to be a modest sized design project in and of itself. Outcomes of supporting effective interaction with the ruler for completely non-visual users may affect the final implementation of basic keyboard nav.
- With previous point in mind, we essentially need reasonably functional keyboard nav for moving ruler situations, but it doesn't need to be perfect since it will have to be revisited for auditory description anyway. 

Would it be useful (@mbarlow12 and @jessegreenberg) to discuss the desired visual look/feel of the focus highlights in Tuesday's keyboard meeting, to at least pin down a goal for the visual design? I'll put this sim down tentatively as something to discuss on Tuesday's agenda, just in cae.
 
Edited to note that this sim already on Tuesday's agenda - looks like we were already thinking the same thing!

**Comment by mbarlow12** [comment]
@jessegreenberg Passing the charges to the common view seems problematic in its large number of arguments (8 if the 2 charges are included) and the fact that creating the charge nodes requires the modelViewTransform (which is instantiated in the common view). 

One solution might be to leave all scene graph construction to the macro and atomic views. The commonView would create the panels and rulers while the atomic view, for instance, would actually add the nodes.

One final option: we could use node.insertChild instead of addChild for the chargeNodes. In this way, we could effectively place the charges on the bottom of the scene graph.

**Comment by mbarlow12** [comment]
Another note on keyboard nav for this (and other similar objects for that matter). The arrow keys are subject to long keydowns that will continually move the ruler. I noticed that it is relatively difficult to incrementally move the ruler a single step. Would it be useful to add movement keys/modifiers that would specifically be used to step moveable objects? Something akin to the difference between the space and return keys? 

If we've already created something like this, then please disregard the above comment. Otherwise, @terracoda @emily-phet should we add this to a future a11y meeting agenda?

**Comment by terracoda** [comment]
It is ideal if the focus highlight is at the same level of the actual focused item, but that could potentially require customizations for every sim with draggable objects.

In a general sense, can this issue be considered related to @jessegreenberg 's question in a11y-research https://github.com/phetsims/a11y-research/issues/69?

**Comment by terracoda** [comment]
Friction is a sim that has a custom highlight, as an example.

**Comment by emily-phet** [comment]
@mbarlow12 Regarding https://github.com/phetsims/coulombs-law/issues/35#issuecomment-356024416, this sounds like a brilliant idea. For rulers (and other moveable objects that need to be "lined up" with other things) being able to move in discrete step sizes would be helpful. If those step sizes were customizable, so we can tailor them to the specific object/task that would be helpful.

**Comment by terracoda** [comment]
@mbarlow12, I agree with @emily-phet this would be very useful. 

I haven't played with the sim much, but I was going to ask what the user is supposed to measure with the ruler and if the ruler should have the same step sizes as the sliders representing the pullers? Or if the ruler should snap to something like the dot representing q1? Again, not sure if the user is supposed to measure the distance between q1 and q 2 or something else.

**Comment by mbarlow12** [comment]
As of now, everything that is moveable snaps to the same grid in the same increments which correspond to half a tick mark on the ruler. However, if you want to move the ruler a single half tick increment with the arrow keys, the button press needs to be very rapid.

My thought was that we should consider creating a separate set of keys or modifiers that, regardless of how long they are pressed, will only move the object a single increment.

For reference, in MAL, you can pause the sim and interact with the step button with either the space bar or enter/return keys. The space bar will only step the sim once while enter/return will continuously step through the animation.

**Comment by jessegreenberg** [comment]
> My thought was that we should consider creating a separate set of keys or modifiers that, regardless of how long they are pressed, will only move the object a single increment.

This sounds really great to me!

> Passing the charges to the common view seems problematic in its large number of arguments (8 if the 2 charges are included)

Agreed, there are a lot of args. I like the idea of leaving scene graph construction to the macro and atomic views. Another possibility is to have a public controlPanelNode in the common view, adding all control panel things to it. Then use Node.moveToFront() in the atomic and macro views to move it in front of the ruler.

**Comment by jessegreenberg** [comment]
> It is ideal if the focus highlight is at the same level of the actual focused item, but that could potentially require customizations for every sim with draggable objects.

@terracoda we could also do this if it is preferable.

**Comment by terracoda** [comment]
@jessegreenberg, thanks for the clarification. Personally, I do think the highlight would look better if it was shown at the same level as the object that has focus, like in Friction or Faraday's Law.

**Comment by mbarlow12** [comment]
@jessegreenberg In https://github.com/phetsims/coulombs-law/commit/b279aae4c9f71640e064532c090b53ba67f8edb8, I simply used Node's insertChild method to place the ChargeNodes and arrows at the bottom of the scene graph. I couldn't find anything to suggest that such a thing was ill advised. For now, this at least allows for the layering we desire; we can revisit the code at review.

**Comment by jessegreenberg** [comment]
Regarding https://github.com/phetsims/coulombs-law/issues/35#issuecomment-356344711, this looks good, thanks @mbarlow12!

From last keyboard navigation meeting we decided that the focus highlight should be layered with the ruler. @mbarlow12 would you mind working on this? In order to to do this, you  will have to create a custom focus highlight and add it to the scene graph (probably as a child of the ruler), then set `focusHighlightLayerable` true for the ruler (defined in the Accessibility trait). Let me know if you run into trouble or have questions.

**Comment by emily-phet** [comment]
@jessegreenberg Just a question - does this mean that anytime we need a focus highlight that is not in the top layer there needs to be a custom focus highlight? Is it possible to create some generalizable feature to focus highlights, or to sim objects to allow this to be handled without a custom approach for each case? (I don't know if this is possible, it's just a thought)

**Comment by jessegreenberg** [comment]
@zepumph did a lot of work to generalize the focus highlights so it is actually more simple than https://github.com/phetsims/coulombs-law/issues/35#issuecomment-356782181 makes it out to be. With the current API it might look something like
```js
// create a custom focus highlight, with default dilation and styling that surrounds this node
var focusHighlight = new FocusHighlightFromNode( this );

//  insert the node into the right place in the scene graph
this.addChild( focusHighlight );

// tell FocusOverlay that the focus highlight for this node should be layered in the scene graph
this.focusHighlightLayerable = true; 
this.focusHighlight = focusHighlight;
```

**Comment by emily-phet** [comment]
@jessegreenberg cool beans. I figured this had already been thought out, but just wanted to check.

**Comment by jessegreenberg** [comment]
Discussed in accessibility meeting:

We talked about a modifier key that would force  a single step.
We talked about a delay on press and hold for the ruler.
We talked about a delay on each step when moving the ruler.

We liked the idea of delays for movement, both at beginning and at every move. Both options should probably be added to  KeyboardDragListener.

**Comment by jessegreenberg** [comment]
From a11y meeting 1/19/18:

- We discussed that  default keyboard step  should be 1/5 cm in macro, 1/5 pm in atomic screen.
- We discussed the shift modifier would step ruler to 1/10 cm in macro, 1/10 pm in atomic screen.
- Remove the interval delay for the ruler in ISLC sims.

**Comment by mbarlow12** [comment]
@jessegreenberg could you review before closing?

**Comment by jessegreenberg** [comment]
Changes look great @mbarlow12, nice job!

I noticed a TODO was added:
```js
      // TODO: consider moving to some kind of reset function
      // reset all press-and-hold variables on keyup
      self.delayComplete = false;
      self.moveOnHoldDelayCounter = 0;
      self.moveOnHoldIntervalCounter = 0;
```

I think we will want to reset flag and timers on blur as well so refactoring sounds great. Would you mind  adding this?

**Comment by mbarlow12** [comment]
@jessegreenberg Sure thing! I forgot I added that in there. I'll have that complete by tomorrow AM.

**Comment by mbarlow12** [comment]
@jessegreenberg we should be good to go.

**Comment by jessegreenberg** [comment]
Thanks @mbarlow12. I switched from self -> this in the instance function since self pointed to the window object. I think we are good to go!
