### ISSUE TITLE
Firefox lags with ruler keyboard dragging

### ISSUE THREAD

**Issue by BryceAG** [phetsims/coulombs-law#41]
Test device: Hanson

Operating System: Windows 10

Browser: Firefox

Problem description: The ruler will lag when being dragged with keyboard navigation. When the arrow key is pressed and held, it will move slower than other objects being pressed and held, and will continue moving after the key is released for a duration. The duration it will continue moving increases proportional to how long the key was held. Because of this I think the sim is taking in commands from the arrow key faster than it follows them, and is just lagging. This only happens with the ruler, as other sliders are smooth, and only on Firefox.

Steps to reproduce: tab to highlight the ruler, press and hold an arrow key for a little while, and release. The ruler will continue moving for a little while longer.

Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Coulomb's Law‬
URL: https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.13/phet/coulombs-law_en_phet.html?accessibility
Version: 1.0.0-dev.13 2018-01-29 22:54:49 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Language: en-US
Window: 1280x606
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"e1350857","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"f616a059","branch":"master"},"coulombs-law":{"sha":"77b8d1e5","branch":"master"},"dot":{"sha":"8d471f40","branch":"master"},"inverse-square-law-common":{"sha":"d135be3b","branch":"master"},"joist":{"sha":"caefa8e2","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"f35ff65e","branch":"master"},"phet-io":{"sha":"59e4fea1","branch":"master"},"phet-io-website":{"sha":"766da99e","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"master"},"phet-io-wrapper-sonification":{"sha":"adfff6d0","branch":"master"},"phet-io-wrapper-visualizing-engagement":{"sha":"14150f43","branch":"master"},"phet-io-wrappers":{"sha":"d11aebf6","branch":"master"},"phetcommon":{"sha":"d33be800","branch":"master"},"query-string-machine":{"sha":"485e174e","branch":"master"},"scenery":{"sha":"70cf829b","branch":"master"},"scenery-phet":{"sha":"bd233bf8","branch":"master"},"sherpa":{"sha":"7a6906fd","branch":"master"},"sun":{"sha":"56f146b1","branch":"master"},"tandem":{"sha":"4de02ea3","branch":"master"}}

**Comment by phet-steele** [comment]
For phetsims/QA/issues/87.

**Comment by jessegreenberg** [comment]
@BryceAG this sounds like a performance problem. Do you notice otherwise general poor performance while running the sim on this platform?

**Comment by lmulhall-phet** [comment]
This is also an issue on Edge.

**Comment by BryceAG** [comment]
@jessegreenberg No, no other performance issues with mouse or keyboard navigation

**Comment by mbarlow12** [comment]
@BryceAG I can't reproduce (on macOS at least) in any browser. There is some mild text/line blurring in FF that sharpens once the dragging is finished and gives the appearance of moving a little further.

The way it's implemented, the arrow keys, if pressed, allow the ruler to move at each simulation step, so we're not registering distinct key presses. If you're releasing an arrow key and seeing significant movement after, I would guess that your browser hasn't yet registered a 'keyup' event yet.

**Comment by ghost** [comment]
@mbarlow12 I can reproduce this issue in Windows, FF. The movement of the ruler after you let go of one of the arrow keys is very noticeable. For instance, if you move the ruler to the top of the page, press down, then let go when it gets about halfway down, it will continue to move all the way down to the bottom of the page without any user input.

**Comment by mbarlow12** [comment]
@lmulhall-phet @BryceAG will either of you be around tomorrow AM? I'd like to go over this in person.  Thanks.

**Comment by ghost** [comment]
@mbarlow12 I’ll be there tomorrow from 9am-1pm.

**Comment by ghost** [comment]
@mbarlow12 Scratch that. I'll be here ~9:15-1:00.

**Comment by mbarlow12** [comment]
Thanks @lmulhall-phet for showing me the issue. I'll create some logging feature that might help us ferret out the problem. This will likely require some input from @jessegreenberg and maybe @jonathanolson. Assigning myself.

**Comment by mbarlow12** [comment]
@ariel-phet I've been having a lot of trouble with this issue. I can't reproduce it, and it has only rarely manifested itself since it was initially found.

Can you advise on level of importance to solve prior to RC ? It might take a long time to peg down a cause and implement a solution. Do we ever release sims with lingering minor QA issues?

**Comment by ariel-phet** [comment]
@mbarlow12 - we do sometimes release sims with minor QA issues that we feel will be "edge cases"

However, in this particular case, I feel like more investigation is warranted for two reasons:
1. Anything dealing with things feeling "smooth" is usually something we do not let slide, as it can affect UX
2. Since we are trying to diligent about keyboard nav, it would be good to know if there is not a larger issue. For instance, we would rather fix something now that might bite us later if we use a similar pattern to outfit another moveable object

That being said...I am seeing some odd things in my own testing. I can reproduce this issue on my Win 10 machine on FF. I am not seeing severe lag (I have not seen the ruler move halfway down the screen after keyup), but have seen noticeable lag.

More interestingly, I have noticed that changing the zoom on the browser window very clearly affects the speed at which the ruler moves with a held down key. This makes me wonder if the current implementation is robust enough.

**Comment by jessegreenberg** [comment]
Thanks for the data point @ariel-phet, no idea why zoom would impact performance or behavior.

**Comment by mbarlow12** [comment]
Agreed, thanks @ariel-phet for clarifying and finding out more. @jessegreenberg and I can work on that next week.

**Comment by jessegreenberg** [comment]
@mbarlow12 and I worked on this today. We tested the sim using Hanson, Dalton, and Bates devices. We did not observe the ruler continue to move after keys were released, but we did see some lag in the dragging.

We made changes to the KeyboardDragListener so that it performs more consistently across platforms with varying framerates. This will benefit sims where the dragging is an important physical interaction (like BASE and JT) because state of sim is no longer tied to framerate. But overall, if zoom impacts framerate, behavior of keyboard dragging should no longer change.

Here is a new version with the update:
https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.16/phet/coulombs-law_en_phet.html?accessibility

There is still some lag with the keyboard while testing with Firefox on Hanson, but overall less lag than while dragging a mass with the touch screen on the same platform.

@ariel-phet @BryceAG @phet-steele can you please test and review this version?

**Comment by ariel-phet** [comment]
@jessegreenberg @mbarlow12 looks better on my win 10 FF. I still do notice zoom affecting keyboard drag. 

For instance, at 30% zoom keyboard dragging is very consistent and smooth

At default zoom and above the ruler sometimes jumps a bit further than expected at times (but stops after keyboard release). It is just a less consistent motion

I can get to everywhere I want to go, but there still seems to be a bit of oddness. We can punt on the oddness for now, and wait to see another case where this arises.

**Comment by arouinfar** [comment]
Tagging `For 1.1+` since the 1.0 release will not include keyboard navigation.

**Comment by KatieWoe** [comment]
@jessegreenberg @mbarlow12 Win 10 firefox for https://github.com/phetsims/QA/issues/203.  I have noticed that on firefox holding the arrow buttons down while dragging the ruler is a bit more jumpy.  I wouldn't really call it lag since not really any slower, its just a bit less smooth.  Might not have noticed if I weren't looking for it honestly.

**Comment by ariel-phet** [comment]
I think this issue can be closed for now. I also tried on Win 7 FF and things seems fine
