### ISSUE TITLE
Toolbox layout

### ISSUE THREAD

**Issue by BryceAG** [phetsims/coulombs-law#47]
In other sims when one toolbox checkbox is dependent on another, it is indented and faded out when the parent checkbox is unchecked. Such as in Charges and Fields:
![image](https://user-images.githubusercontent.com/15327201/35826648-92910472-0a76-11e8-9402-7c2e64c469c3.png)

In this sim, Scientific Notation is dependent on Show Values, but is neither indented nor faded out when show values is unchecked:
![image](https://user-images.githubusercontent.com/15327201/35826710-c97e8914-0a76-11e8-9f9c-ce098a88dbea.png)

However, in this sim there are no other checkboxes below the child checkbox, and so indenting might appear as though it is just misaligned. The font size could be changed to better show it is a subset, but this might also look weird. Any thoughts?

related to phetsims/QA#87.

**Comment by arouinfar** [comment]
Great observation @BryceAG! Scientific Notation's visibility depends on Show Values, so it would generally be indented. 

Since the panel only has two checkboxes, I think it looks a bit more natural if "Scientific Notation" is slightly smaller. We'll also need to expand the panel a little bit, but there's plenty of space for that.

![image](https://user-images.githubusercontent.com/8419308/35885462-1cf6e8dc-0b4b-11e8-9e37-93fdb853464b.png)

Here's a comparison between equal font sizes (top) and "Scientific Notation" reduced by 2pt (bottom).
![image](https://user-images.githubusercontent.com/8419308/35885537-6a076aca-0b4b-11e8-976b-b44f696f0b9e.png)

Any change we make here would also apply to GFL, as it also has a Scientific Notation option.
![image](https://user-images.githubusercontent.com/8419308/35886328-e9f919b6-0b4d-11e8-84b8-b2356c42d729.png)

What do you think @ariel-phet?

**Comment by arouinfar** [comment]
After some discussion with @ariel-phet we decided against indenting scientific notation. While @BryceAG is absolutely correct that logically, scientific notation should be indented, ISLC sims are a bit different. 

When there's a long list of checkboxes, as in CAF, the indentation is visually helpful and is better UX. In ISLC, the small number of checkboxes makes the indentation look like a UI mistake. Since Values is on by default, toggling Scientific Notation will lead to something visually happening on screen. Therefore, not indenting the checkbox is unlikely to cause UX problems.

Once again, great observation @BryceAG!
