### ISSUE TITLE
Navigation bar icons look bad in Firefox

### ISSUE THREAD

**Issue by ghost** [phetsims/coulombs-law#75]
For https://github.com/phetsims/QA/issues/210. MacBook Air, Early 2015. macOS 10.14.

Firefox 62.0.3:
![firefox](https://user-images.githubusercontent.com/31285590/47116879-20731700-d220-11e8-9f7c-a24ea3560324.png)

Chrome 70.0.3538.67:
![chrome](https://user-images.githubusercontent.com/31285590/47116891-279a2500-d220-11e8-9252-697c7c471339.png)

Safari 12.0:
![safari](https://user-images.githubusercontent.com/31285590/47116914-341e7d80-d220-11e8-979c-81b0c936cd66.png)

I'm not sure if design:polish is the correct label for this. Maybe it has something to do with FF? Or maybe it's device-specific. I'll try to find out if it's device-specific.

EDIT: It's not device-specifc.

**Comment by arouinfar** [comment]
Is it possible that the icons are super aliased because they are being scaled down from the home screen icons? I re-exported the image files for the navbar at a lower resolution. 

@mbarlow12 can you try these instead?
[atomic_scale_screen_icon_navbar.png](https://user-images.githubusercontent.com/8419308/47118808-cd9c5e00-d225-11e8-85be-88131477ef97.png)
[macro_scale_screen_icon_navbar.png](https://user-images.githubusercontent.com/8419308/47118809-cd9c5e00-d225-11e8-96cf-f269f383cf3f.png)

**Comment by mbarlow12** [comment]
Should be fixed in the new rc release:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html

**Comment by KatieWoe** [comment]
Looks good to me 1.0.0-rc.4.  Perhaps a bit more pixelated in firefox than chrome, but much better.

**Comment by arouinfar** [comment]
Firefox generally has poorer rendering than other browsers, and rc.4 is a definite improvement. I don't think there's anything else we need to do for this issue.
