### ISSUE TITLE
Boxes overlap

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#83]
For https://github.com/phetsims/QA/issues/221.  Likely connected to https://github.com/phetsims/coulombs-law/issues/81.  When stringTest=double but not long the Charge 2 box and the Force values box overlap.  Discovered on an iPad, but occurs elsewhere.  See image bellow.
![img_1340](https://user-images.githubusercontent.com/41024075/49112194-5c51c100-f24f-11e8-9ca8-43188f07c001.PNG)

**Comment by arouinfar** [comment]
Good catch @KatieWoe!

Comparing Macro Scale to Atomic Scale, it seems that the problem is that the Charge panels haven't been given a maxWidth. Macro scale has longer units (μC) compared to Atomic Scale (e), which leads to a wider panel.
![image](https://user-images.githubusercontent.com/8419308/49113838-c2d8de00-f253-11e8-8bb8-432e9d46eafd.png)
![image](https://user-images.githubusercontent.com/8419308/49113778-a177f200-f253-11e8-9dd5-bc737636d807.png)

However, I'm not so sure the Charge panels need to expand at all, since there's quite a bit of white space around "Charge".
![image](https://user-images.githubusercontent.com/8419308/49113979-3aa70880-f254-11e8-959c-c7257a02ee15.png)

**Comment by KatieWoe** [comment]
1.0.0-rc.6 looks good.
