### ISSUE TITLE
[Atomic Scale] Use MathSymbols.TIMES in scale bar readout

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#99]
For https://github.com/phetsims/QA/issues/243

@phet-steele noticed that the multiplication symbol used in the scale bar on the Atomic Scale screen is the letter x, not MathSymbols.TIMES. This was addressed for scientific notation in https://github.com/phetsims/inverse-square-law-common/issues/50, but it looks like we missed this one.

![image](https://user-images.githubusercontent.com/8419308/50315386-cab12a00-046f-11e9-99c3-77fcc4e026c4.png)

**Comment by jessegreenberg** [comment]
@mbarlow12 is it possible to use MathSymbols.TIMES for this?

**Comment by mbarlow12** [comment]
My hesitation there is that the text is coming from the `...string_en.json` file at the moment, so I can't use the MathSymbols object. Since it's static, I'd prefer to keep it in the strings file, and there is ample precedent for including minor HTML within the translatable strings.

I can still split the text into different nodes to allow for using MathSymbols, but that seems overkill for this case. Unless, I hear otherwise, I'll plan to move forward with `&times;` in the string.

**Comment by arouinfar** [comment]
That all sounds reasonable to me @mbarlow12. 

I noticed the `atomicLegendScale` and `macroLegendScale` look a bit odd in the [string file](https://github.com/phetsims/coulombs-law/blob/master/coulombs-law-strings_en.json#L32). Only the units should be translatable, not the numbers. 

```
 "units.atomicLegendScale": {
    "value": "10 pm"
  },
  "units.macroLegendScale": {
    "value": "1 cm"
  },
```

Compare to the `cmValue` and `nmValue` in [wave-interference](https://github.com/phetsims/wave-interference/blob/master/wave-interference-strings_en.json#L50).
<img width="104" alt="screen shot 2018-12-22 at 3 00 54 pm" src="https://user-images.githubusercontent.com/8419308/50378953-6f5f7300-05fa-11e9-93ee-da538b8e02bb.png"> <img width="124" alt="screen shot 2018-12-22 at 3 01 09 pm" src="https://user-images.githubusercontent.com/8419308/50378954-6f5f7300-05fa-11e9-9623-3d5f75992026.png">

```
"cmValue": {
    "value": "{0} cm"
  },
  "nmValue": {
    "value": "{0} nm"
  },
```
This seems like a really minor change, so I would be happy to test on master before we proceed with 1.0.

**Comment by mbarlow12** [comment]
@arouinfar I think the use case is  a little different. Those patterns are reused throughout the wave interference sim with varying values (e.g. see the double slit screen control panel). Since the string for the CL legend never changes, it seems unnecessary to dynamically fill it with a constant value.

I'd say it's more similar to the millisecond or femtosecond conversion strings:
```json

  "millisecondConversion": {
    "value": "1 ms = 10<sup>-3</sup> s"
  },
  "femtosecondConversion": {
    "value": "1 fs = 10<sup>-15</sup> s"
  }
```

**Comment by mbarlow12** [comment]
@arouinfar I went forward with publishing the sim as-is since there appears to be precedent for not using patterns for static strings.

**Comment by arouinfar** [comment]
Thanks for the clarification @mbarlow12. It seemed odd that the numbers were included in the string to be translated, but the secondConversion strings are an interesting parallel.
